### ISSUE TITLE
Please fork the original repo instead of reuploading

### ISSUE THREAD

**Issue by arifszn** [ghulamrasuldev/my-website#1]
To support the author, please fork the [original repo](https://github.com/arifszn/ezprofile) instead of reuploading. It would be very much appreciated. You can do all things in the forked repo. Star the repo too if it helps. Thanks.

**Comment by ghulamrasuldev** [comment]
hi, i never used website template like this. so i mentioned their name in
my online website www.ghulamrasuldev.com.

Also is there any.other way to solve this issue?

**Comment by arifszn** [comment]
I am the author of [ezProfile](https://github.com/arifszn/ezprofile) by the way. The way it is now, it's fine. It's just a request to fork and star the repo. Thanks.

**Comment by ghulamrasuldev** [comment]
Yes thank you so much for the awesome website.  i will fork it, star it
share it to social media.  but its hard for me to delete this repo.
actually am not a web developer and it was very hard for making it live :(

**Comment by arifszn** [comment]
Then it's ok. No need to fork it. I am closing this issue.

**Comment by ghulamrasuldev** [comment]
Thanm You so much, i will be forking liking coz you deserve:)
